EQUIPMENT = [
    {"slug": "bodyweight", "category": "bodyweight", "translations": {"fr": {"name": "Poids du corps", "description": "Aucun matériel requis."}, "en": {"name": "Bodyweight", "description": "No equipment required."}}},
    {"slug": "dumbbells", "category": "strength", "translations": {"fr": {"name": "Haltères", "description": "Haltères libres."}, "en": {"name": "Dumbbells", "description": "Free dumbbells."}}},
    {"slug": "barbell", "category": "strength", "translations": {"fr": {"name": "Barre", "description": "Barre de musculation."}, "en": {"name": "Barbell", "description": "Barbell."}}},
    {"slug": "plates", "category": "strength", "translations": {"fr": {"name": "Disques", "description": "Disques de charge."}, "en": {"name": "Plates", "description": "Weight plates."}}},
    {"slug": "bench", "category": "strength", "translations": {"fr": {"name": "Banc", "description": "Banc d'entraînement."}, "en": {"name": "Bench", "description": "Training bench."}}},
    {"slug": "rack", "category": "strength", "translations": {"fr": {"name": "Rack", "description": "Support de chargement."}, "en": {"name": "Rack", "description": "Loading support."}}},
    {"slug": "smith_machine", "category": "strength", "translations": {"fr": {"name": "Smith machine", "description": "Machine de musculation guidée."}, "en": {"name": "Smith machine", "description": "Guided strength machine."}}},
    {"slug": "cable_machine", "category": "strength", "translations": {"fr": {"name": "Câble", "description": "Machine à câbles."}, "en": {"name": "Cable machine", "description": "Cable machine."}}},
    {"slug": "kettlebell", "category": "strength", "translations": {"fr": {"name": "Kettlebell", "description": "Kettlebell."}, "en": {"name": "Kettlebell", "description": "Kettlebell."}}},
    {"slug": "resistance_band", "category": "mobility", "translations": {"fr": {"name": "Bande élastique", "description": "Bande de résistance."}, "en": {"name": "Resistance band", "description": "Resistance band."}}},
    {"slug": "pull_up_bar", "category": "bodyweight", "translations": {"fr": {"name": "Barre de traction", "description": "Barre pour tractions."}, "en": {"name": "Pull-up bar", "description": "Bar for pull-ups."}}},
    {"slug": "dip_bar", "category": "bodyweight", "translations": {"fr": {"name": "Barres de dips", "description": "Barres pour dips."}, "en": {"name": "Dip bar", "description": "Bars for dips."}}},
    {"slug": "medicine_ball", "category": "power", "translations": {"fr": {"name": "Medicine ball", "description": "Ballon de force."}, "en": {"name": "Medicine ball", "description": "Medicine ball."}}},
    {"slug": "plyo_box", "category": "power", "translations": {"fr": {"name": "Boîte plyo", "description": "Boîte pour sauts et puissance."}, "en": {"name": "Plyo box", "description": "Box for jumps and power work."}}},
    {"slug": "jump_rope", "category": "cardio", "translations": {"fr": {"name": "Corde à sauter", "description": "Corde pour cardio et coordination."}, "en": {"name": "Jump rope", "description": "Rope for cardio and coordination."}}},
    {"slug": "treadmill", "category": "cardio", "translations": {"fr": {"name": "Tapis roulant", "description": "Course intérieure."}, "en": {"name": "Treadmill", "description": "Indoor running."}}},
    {"slug": "bike", "category": "cardio", "translations": {"fr": {"name": "Vélo", "description": "Vélo de route ou de ville."}, "en": {"name": "Bike", "description": "Road or city bike."}}},
    {"slug": "stationary_bike", "category": "cardio", "translations": {"fr": {"name": "Vélo stationnaire", "description": "Vélo de salle."}, "en": {"name": "Stationary bike", "description": "Indoor exercise bike."}}},
    {"slug": "rowing_machine", "category": "cardio", "translations": {"fr": {"name": "Rameur", "description": "Machine à rameur."}, "en": {"name": "Rowing machine", "description": "Rowing machine."}}},
    {"slug": "elliptical", "category": "cardio", "translations": {"fr": {"name": "Elliptique", "description": "Machine à mouvement continu."}, "en": {"name": "Elliptical", "description": "Cardio elliptical machine."}}},
    {"slug": "swimming_pool", "category": "aquatic", "translations": {"fr": {"name": "Piscine", "description": "Bassin de natation."}, "en": {"name": "Swimming pool", "description": "Swimming basin."}}},
    {"slug": "boxing_bag", "category": "combat", "translations": {"fr": {"name": "Sac de boxe", "description": "Sac pour coups et endurance."}, "en": {"name": "Boxing bag", "description": "Punching bag for technique and conditioning."}}},
    {"slug": "gloves", "category": "combat", "translations": {"fr": {"name": "Gants", "description": "Gants de boxe."}, "en": {"name": "Gloves", "description": "Boxing gloves."}}},
    {"slug": "football", "category": "ball", "translations": {"fr": {"name": "Ballon de football", "description": "Ballon de football."}, "en": {"name": "Football", "description": "Association football."}}},
    {"slug": "basketball", "category": "ball", "translations": {"fr": {"name": "Ballon de basket", "description": "Ballon de basket."}, "en": {"name": "Basketball", "description": "Basketball."}}},
    {"slug": "tennis_racket", "category": "racquet", "translations": {"fr": {"name": "Raquette de tennis", "description": "Raquette de tennis."}, "en": {"name": "Tennis racket", "description": "Tennis racket."}}},
    {"slug": "badminton_racket", "category": "racquet", "translations": {"fr": {"name": "Raquette de badminton", "description": "Raquette de badminton."}, "en": {"name": "Badminton racket", "description": "Badminton racket."}}},
    {"slug": "mat", "category": "mobility", "translations": {"fr": {"name": "Tapis", "description": "Tapis d'exercice."}, "en": {"name": "Mat", "description": "Exercise mat."}}},
    {"slug": "foam_roller", "category": "recovery", "translations": {"fr": {"name": "Rouleau en mousse", "description": "Auto-massage et récupération."}, "en": {"name": "Foam roller", "description": "Foam rolling for recovery."}}},
]

ENVIRONMENT = [
    {"slug": "home", "category": "indoor", "translations": {"fr": {"name": "Maison", "description": "Entraînement à domicile."}, "en": {"name": "Home", "description": "Home environment."}}},
    {"slug": "gym", "category": "indoor", "translations": {"fr": {"name": "Salle", "description": "Salle de musculation."}, "en": {"name": "Gym", "description": "Gym environment."}}},
    {"slug": "outdoor", "category": "outdoor", "translations": {"fr": {"name": "Extérieur", "description": "Entraînement extérieur."}, "en": {"name": "Outdoor", "description": "Outdoor environment."}}},
    {"slug": "track", "category": "outdoor", "translations": {"fr": {"name": "Piste", "description": "Piste d'athlétisme."}, "en": {"name": "Track", "description": "Athletics track."}}},
    {"slug": "road", "category": "outdoor", "translations": {"fr": {"name": "Route", "description": "Course sur route."}, "en": {"name": "Road", "description": "Road running."}}},
    {"slug": "trail", "category": "outdoor", "translations": {"fr": {"name": "Sentier", "description": "Terrain naturel."}, "en": {"name": "Trail", "description": "Natural terrain."}}},
    {"slug": "stadium", "category": "outdoor", "translations": {"fr": {"name": "Stade", "description": "Stade et grands espaces."}, "en": {"name": "Stadium", "description": "Stadium environment."}}},
    {"slug": "football_field", "category": "outdoor", "translations": {"fr": {"name": "Terrain de football", "description": "Terrain de football."}, "en": {"name": "Football field", "description": "Football pitch."}}},
    {"slug": "basketball_court", "category": "outdoor", "translations": {"fr": {"name": "Terrain de basket", "description": "Terrain de basket."}, "en": {"name": "Basketball court", "description": "Basketball court."}}},
    {"slug": "tennis_court", "category": "outdoor", "translations": {"fr": {"name": "Court de tennis", "description": "Court de tennis."}, "en": {"name": "Tennis court", "description": "Tennis court."}}},
    {"slug": "pool", "category": "aquatic", "translations": {"fr": {"name": "Piscine", "description": "Piscine olympique ou publique."}, "en": {"name": "Pool", "description": "Pool environment."}}},
    {"slug": "combat_gym", "category": "indoor", "translations": {"fr": {"name": "Salle de combat", "description": "Salle de combat."}, "en": {"name": "Combat gym", "description": "Combat training room."}}},
]
