from app.models.enums import DifficultyLevel, TrainingType

E, M, H = DifficultyLevel.EASY, DifficultyLevel.MEDIUM, DifficultyLevel.HARD
ST, HY, PW, CD, EN, SP, AG, TC, MB, RC, IV = (
    TrainingType.STRENGTH,
    TrainingType.HYPERTROPHY,
    TrainingType.POWER,
    TrainingType.CARDIO,
    TrainingType.ENDURANCE,
    TrainingType.SPEED,
    TrainingType.AGILITY,
    TrainingType.TECHNIQUE,
    TrainingType.MOBILITY,
    TrainingType.RECOVERY,
    TrainingType.INTERVAL,
)


def _e(slug, sport, category, types, difficulty, fr, en, equipment=None):
    return {
        "slug": slug,
        "sport_slug": sport,
        "category": category,
        "equipment": equipment,
        "training_types": types,
        "difficulty": difficulty,
        "translations": {
            "fr": {"name": fr[0], "description": fr[1]},
            "en": {"name": en[0], "description": en[1]},
        },
    }


PROGRAM_EXERCISES_CATALOG = [
    _e("rotations_poignets_chevilles", None, "mobility", [MB], E,
       ("Rotations poignets et chevilles", "Mobilisation articulaire légère en échauffement."),
       ("Wrist and ankle circles", "Light joint mobility used as a warm-up.")),
    _e("directs_jab_cross", "arts_martiaux", "technique", [TC, SP, AG], E,
       ("Directs jab/cross en déplacement", "Coups directs en avançant, reculant et pivotant."),
       ("Jab/cross on the move", "Straight punches while stepping and pivoting."),
       "gloves"),
    _e("pompes_genoux", None, "chest", [ST, EN], E,
       ("Pompes sur les genoux", "Pompes adaptées, genoux au sol."),
       ("Knee push-ups", "Regressed push-up with knees on the floor.")),
    _e("squats_poids_corps", None, "legs", [ST, EN], E,
       ("Squats au poids du corps", "Flexions de jambes sans charge."),
       ("Bodyweight squats", "Unloaded squat pattern.")),
    _e("gainage_coudes", None, "core", [ST, MB], E,
       ("Gainage frontal sur les coudes", "Planche basse, alignement tête-bassin-talons."),
       ("Forearm plank", "Low plank holding a straight body line.")),
    _e("pas_chasses_croises", "arts_martiaux", "agility", [AG, SP], E,
       ("Pas chassés et pas croisés", "Déplacements latéraux sur échelle ou cônes."),
       ("Shuffle and crossover steps", "Lateral footwork on a ladder or cones.")),
    _e("birddog", None, "core", [ST, MB], E,
       ("Bird dog", "Extension opposée bras/jambe à quatre pattes."),
       ("Bird dog", "Opposite arm and leg reach from quadruped.")),
    _e("thrusters", "fitness", "full_body", [PW, ST, CD], M,
       ("Thrusters", "Squat + développé explosif en un seul mouvement."),
       ("Thrusters", "Squat into an explosive overhead press."),
       "dumbbells"),
    _e("slam_ball", "fitness", "power", [PW, CD], M,
       ("Slam ball", "Lancer violent du ballon au sol, toute la chaîne."),
       ("Slam ball", "Explosive overhead slam into the floor."),
       "medicine_ball"),
    _e("pompes_explosives", "fitness", "chest", [PW, ST], M,
       ("Pompes explosives", "Poussée rapide jusqu'à décoller les mains."),
       ("Explosive push-ups", "Fast press until the hands leave the floor.")),
    _e("gainage_dynamique", None, "core", [ST, CD], M,
       ("Gainage dynamique", "Planche avec mouvements contrôlés du tronc."),
       ("Dynamic plank", "Plank with controlled torso movement.")),
    _e("light_sparring_paos", "arts_martiaux", "technique", [TC, AG, EN], M,
       ("Light sparring / travail aux paos", "Échanges contrôlés ou frappes sur cibles."),
       ("Light sparring / pad work", "Controlled exchanges or pad striking."),
       "gloves"),
    _e("goblet_squat", "musculation", "legs", [ST, HY], E,
       ("Goblet squat", "Squat tenu devant la poitrine, haltère ou kettlebell."),
       ("Goblet squat", "Squat holding a weight at chest height."),
       "kettlebell"),
    _e("sauts_verticaux", "fitness", "power", [PW, AG], M,
       ("Sauts verticaux", "Détente verticale maximale, réception souple."),
       ("Vertical jumps", "Maximal vertical jump with a soft landing.")),
    _e("broad_jumps", "fitness", "power", [PW, SP], M,
       ("Broad jumps", "Sauts en longueur sans élan, hanches explosives."),
       ("Broad jumps", "Standing long jumps driven by the hips.")),
    _e("rdl_roumain", "musculation", "legs", [ST, HY], M,
       ("Soulevé de terre roumain", "Charnière de hanche, ischios et fessiers."),
       ("Romanian deadlift", "Hip hinge targeting hamstrings and glutes."),
       "barbell"),
    _e("glute_bridge", None, "legs", [ST, MB], E,
       ("Pont fessier", "Extension de hanche au sol, fessiers serrés en haut."),
       ("Glute bridge", "Hip extension on the floor, squeeze at the top.")),
    _e("rounds_shadow_lutte_sac", "arts_martiaux", "technique", [TC, CD, AG], M,
       ("Rounds shadow / lutte / sac / sprawls", "Simulation de combat en rounds mixtes."),
       ("Shadow, clinch, bag and sprawl rounds", "Mixed fight-simulation rounds."),
       "gloves"),
    _e("box_jumps", "fitness", "power", [PW, AG], M,
       ("Box jumps", "Sauts sur une box, réception stable."),
       ("Box jumps", "Jump onto a box and stick the landing."),
       "plyo_box"),
    _e("depth_jumps", "fitness", "power", [PW], H,
       ("Depth jumps", "Saut en contrebas puis rebond vertical immédiat."),
       ("Depth jumps", "Drop from a box then rebound into a vertical jump."),
       "plyo_box"),
    _e("medball_chest_pass", "fitness", "power", [PW, ST], M,
       ("Chest pass médecine-ball contre mur", "Poussée explosive des pectoraux et des triceps."),
       ("Medicine-ball chest pass", "Explosive chest pass into a wall."),
       "medicine_ball"),
    _e("pompes_clappees", "fitness", "chest", [PW], H,
       ("Pompes clappées", "Pompe plyométrique avec claquement des mains."),
       ("Clapping push-ups", "Plyometric push-up with a clap.")),
    _e("landmine_press", "musculation", "shoulders", [PW, ST], M,
       ("Landmine press explosif", "Développé unilatéral explosif sur barre pivot."),
       ("Explosive landmine press", "One-arm explosive press on a landmine."),
       "barbell"),
    _e("landmine_rotations", "musculation", "core", [ST, PW], M,
       ("Landmine rotations", "Rotations du tronc contre résistance."),
       ("Landmine rotations", "Resisted torso rotations."),
       "barbell"),
    _e("tractions_lestees", "musculation", "back", [ST, HY], H,
       ("Tractions lestées", "Tractions avec charge additionnelle."),
       ("Weighted pull-ups", "Pull-ups with added load."),
       "pull_up_bar"),
    _e("sparring_intensif", "arts_martiaux", "technique", [TC, SP, IV], H,
       ("Sparring haute intensité", "Rounds à intensité réelle, 5x3 min ou 3x5 min."),
       ("High-intensity sparring", "Live rounds, 5x3 min or 3x5 min."),
       "gloves"),
    _e("sprawls_burpees", "arts_martiaux", "full_body", [IV, PW, CD], H,
       ("Sprawls / burpees à épuisement", "Finisseur de combat jusqu'à fatigue."),
       ("Sprawls / burpees to fatigue", "Fight finisher taken near exhaustion.")),
    _e("t_spine_mobility", None, "mobility", [MB, RC], E,
       ("Mobilité thoracique (T-spine)", "Rotations et extensions de la cage thoracique."),
       ("T-spine mobility", "Thoracic rotations and extensions.")),
    _e("cervicales_bande", None, "mobility", [ST, MB], E,
       ("Renforcement cervicales avec bande", "Résistance légère pour la nuque."),
       ("Banded neck strengthening", "Light band resistance for the neck."),
       "resistance_band"),
    _e("coiffe_rotateurs", None, "shoulders", [ST, MB], E,
       ("Travail de la coiffe des rotateurs", "Rotations externes contrôlées, bande ou haltères légers."),
       ("Rotator cuff work", "Controlled external rotations with a light band."),
       "resistance_band"),
    _e("isometrie_grand_ecart", "arts_martiaux", "mobility", [MB], M,
       ("Isométrie sur grand écart", "Maintiens longs pour ouvrir les hanches."),
       ("Splits isometric holds", "Long holds to open the hips.")),
    _e("developpe_militaire_halteres", "musculation", "shoulders", [ST, HY], M,
       ("Développé militaire haltères", "Poussée verticale unilatérale plus naturelle pour les épaules."),
       ("Dumbbell overhead press", "Vertical press with a more natural shoulder path."),
       "dumbbells"),
    _e("russian_twists", "musculation", "core", [HY, ST], E,
       ("Russian twists", "Rotations du buste assis, charge optionnelle."),
       ("Russian twists", "Seated torso rotations, optional load.")),
    _e("fentes_bulgares", "musculation", "legs", [HY, ST], M,
       ("Fentes bulgares haltères", "Fente arrière pied surélevé, une jambe à la fois."),
       ("Bulgarian split squats", "Rear-foot elevated split squat."),
       "dumbbells"),
    _e("tirage_vertical", "musculation", "back", [HY, ST], E,
       ("Tirage vertical poulie haute", "Grand dorsal en traction guidée."),
       ("Lat pulldown", "Guided vertical pull for the lats."),
       "cable_machine"),
    _e("tractions_supination", "musculation", "back", [ST, HY], M,
       ("Tractions supination", "Prise inversée, dos et biceps."),
       ("Chin-ups", "Supinated pull-ups for back and biceps."),
       "pull_up_bar"),
    _e("souleve_terre_jambes_tendues", "musculation", "legs", [HY, ST], M,
       ("Soulevé de terre jambes tendues", "Ischios en charnière, genoux souples."),
       ("Stiff-leg deadlift", "Hamstring hinge with soft knees."),
       "barbell"),
    _e("leg_extension", "musculation", "legs", [HY], E,
       ("Leg extension", "Isolation des quadriceps à la machine."),
       ("Leg extension", "Quad isolation on the machine."),
       "smith_machine"),
    _e("mollets_debout", "musculation", "legs", [HY], E,
       ("Mollets debout", "Élévations sur la pointe des pieds."),
       ("Standing calf raises", "Plantar flexion under load.")),
    _e("ecartes_poulie", "musculation", "chest", [HY], E,
       ("Écartés poulie vis-à-vis", "Étirement et contraction des pectoraux."),
       ("Cable flyes", "Chest stretch and squeeze on cables."),
       "cable_machine"),
    _e("elevations_laterales_cable", "musculation", "shoulders", [HY], E,
       ("Élévations latérales câble", "Deltoïde moyen sous tension continue."),
       ("Cable lateral raises", "Side delts under constant tension."),
       "cable_machine"),
    _e("extension_triceps_overhead", "musculation", "arms", [HY], E,
       ("Extensions triceps au-dessus de la tête", "Longue portion du triceps."),
       ("Overhead triceps extension", "Long-head triceps emphasis."),
       "cable_machine"),
    _e("rowing_unilateral", "musculation", "back", [HY, ST], M,
       ("Rowing unilatéral haltère", "Tirage un bras, dos épais et stable."),
       ("Single-arm dumbbell row", "Unilateral row for thickness and stability."),
       "dumbbells"),
    _e("tirage_poitrine_prise_serree", "musculation", "back", [HY], E,
       ("Tirage poitrine prise serrée", "Milieu du dos et biceps."),
       ("Close-grip chest-supported row", "Mid-back and biceps focus."),
       "cable_machine"),
    _e("oiseau_halteres", "musculation", "shoulders", [HY], E,
       ("Oiseau haltères", "Arrière d'épaule, buste penché."),
       ("Rear-delt flyes", "Bent-over rear deltoid raises."),
       "dumbbells"),
    _e("curl_ez", "musculation", "arms", [HY], E,
       ("Curl barre EZ", "Biceps avec prise plus confortable pour les poignets."),
       ("EZ-bar curl", "Biceps curl with a wrist-friendly grip."),
       "barbell"),
    _e("curl_marteau", "musculation", "arms", [HY], E,
       ("Curl marteau", "Brachial et avant-bras, haltères neutres."),
       ("Hammer curl", "Neutral-grip curl for brachialis and forearms."),
       "dumbbells"),
    _e("squat_profond", "musculation", "legs", [ST, HY], H,
       ("Squat profond", "Flexion complète, dos gainé."),
       ("Deep squat", "Full-depth squat with a braced torso."),
       "barbell"),
    _e("hip_thrust", "musculation", "legs", [HY, ST], M,
       ("Hip thrust à la barre", "Extension de hanche lourde pour les fessiers."),
       ("Barbell hip thrust", "Heavy hip extension for the glutes."),
       "barbell"),
    _e("leg_curl_assis", "musculation", "legs", [HY], E,
       ("Leg curl assis", "Ischios en isolation, hanche fléchie."),
       ("Seated leg curl", "Hamstring isolation with a flexed hip."),
       "smith_machine"),
    _e("mollets_presse", "musculation", "legs", [HY], E,
       ("Mollets à la presse", "Mollets sous charge guidée."),
       ("Leg-press calf raises", "Calves under a guided load."),
       "smith_machine"),
    _e("releves_jambes_suspendu", "musculation", "core", [ST, HY], M,
       ("Relevés de jambes suspendu", "Abdominaux inférieurs en suspension."),
       ("Hanging leg raises", "Lower abs from a dead hang."),
       "pull_up_bar"),
    _e("fentes_sautees", "fitness", "legs", [PW, EN], M,
       ("Fentes sautées", "Fentes plyométriques, une jambe puis l'autre."),
       ("Jumping lunges", "Alternating plyometric lunges.")),
    _e("mollets_une_jambe", None, "legs", [ST, EN], E,
       ("Mollets sur une jambe", "Élévation unilatérale avec pause en haut."),
       ("Single-leg calf raises", "Unilateral raise with a pause at the top.")),
    _e("step_ups_charges", "musculation", "legs", [ST, EN], M,
       ("Step-ups chargés", "Montées sur banc avec haltères."),
       ("Weighted step-ups", "Box step-ups holding dumbbells."),
       "dumbbells"),
    _e("gainage_lateral", None, "core", [ST, MB], E,
       ("Gainage latéral", "Planche sur le côté, hanche haute."),
       ("Side plank", "Lateral plank with hips lifted.")),
    _e("bridge_une_jambe", None, "legs", [ST, MB], E,
       ("Bridge sur une jambe", "Pont fessier unilatéral."),
       ("Single-leg glute bridge", "Unilateral hip bridge.")),
    _e("sprints_en_v", "football", "speed", [SP, AG], M,
       ("Sprints en V", "Accélérations avec changement de direction en V."),
       ("V-cut sprints", "Accelerations with a V-shaped cut.")),
    _e("sauts_lateraux_haies", "football", "power", [PW, AG], M,
       ("Sauts latéraux haie basse", "Pliométrie latérale par-dessus une haie."),
       ("Lateral hurdle hops", "Side-to-side hops over a low hurdle.")),
    _e("nordics_hamstring", "football", "legs", [ST], H,
       ("Nordic hamstring curls", "Curl ischio excentrique au sol, partenaire ou ancrage."),
       ("Nordic hamstring curls", "Eccentric hamstring curl from the knees.")),
    _e("copenhagen_plank", "football", "legs", [ST, MB], M,
       ("Copenhagen plank / adducteurs", "Gainage latéral pour les adducteurs."),
       ("Copenhagen plank", "Side-lying adductor plank.")),
    _e("proprio_bosu", "football", "legs", [MB, ST], E,
       ("Proprioception BOSU / plateau instable", "Équilibre unipodal sur surface instable."),
       ("BOSU proprioception", "Single-leg balance on an unstable surface."),
       "bosu"),
    _e("gainage_rotations_buste", None, "core", [ST], E,
       ("Gainage dynamique avec rotations", "Planche et rotations contrôlées du buste."),
       ("Plank with torso rotations", "Dynamic plank adding controlled twists.")),
    _e("echelle_agilite_footwork", "football", "agility", [AG, SP], E,
       ("Échelle d'agilité (pas chassés, in-out)", "Footwork rapide pieds joints et latéraux."),
       ("Agility ladder footwork", "In-out, shuffles and two-foot hops."),
       "agility_ladder"),
    _e("cat_cow", None, "mobility", [MB, RC], E,
       ("Cat-cow", "Mobilisation douce de la colonne en flexion/extension."),
       ("Cat-cow", "Gentle spinal flexion and extension.")),
    _e("squats_chaise", None, "legs", [ST], E,
       ("Squats assis-debout sur chaise", "Assise et relevé contrôlés, amplitude limitée."),
       ("Sit-to-stand from a chair", "Controlled stand-up with a limited range.")),
    _e("pompes_inclinees", None, "chest", [ST], E,
       ("Pompes inclinées (table ou mur)", "Pompes facilitées, mains surélevées."),
       ("Incline push-ups", "Hands elevated on a table or wall.")),
    _e("rowing_elastique", None, "back", [ST, HY], E,
       ("Rowing avec bande élastique", "Tirage horizontal sans machine."),
       ("Band row", "Horizontal pull with a resistance band."),
       "resistance_band"),
    _e("developpe_epaules_leger", None, "shoulders", [ST, HY], E,
       ("Développé épaules léger", "Bouteilles d'eau ou petits haltères."),
       ("Light shoulder press", "Water bottles or very light dumbbells.")),
    _e("gainage_genoux", None, "core", [ST, MB], E,
       ("Gainage genoux au sol", "Planche adaptée, genoux posés."),
       ("Kneeling plank", "Regressed plank with knees down.")),
    _e("jumping_jacks", "fitness", "cardio", [CD, IV], E,
       ("Jumping jacks", "Écartés sautés, finisseur métabolique simple."),
       ("Jumping jacks", "Simple metabolic finisher.")),
    _e("respiration_diaphragmatique", None, "recovery", [RC, MB], E,
       ("Respiration diaphragmatique", "Respiration ventrale lente pour récupérer."),
       ("Diaphragmatic breathing", "Slow belly breathing for recovery.")),
    _e("travail_postural", None, "mobility", [MB, RC], E,
       ("Travail postural", "Alignement tête-épaules-bassin, mobilité articulaire."),
       ("Postural work", "Head-shoulder-hip alignment and joint mobility.")),
    _e("fentes_marchees", "musculation", "legs", [ST, HY, EN], M,
       ("Fentes marchées", "Fentes dynamiques en déplacement alterné."),
       ("Walking lunges", "Dynamic lunges stepping forward continuously."),
       "dumbbells"),
    _e("pompes_lestees", "musculation", "chest", [ST, HY], M,
       ("Pompes lestées", "Pompes au sol avec disque ou veste lestée sur le dos."),
       ("Weighted push-ups", "Push-ups with a plate or weight vest on the back."),
       "weight_vest"),
    _e("dips_lestes", "musculation", "chest", [ST, HY], H,
       ("Dips lestés", "Dips aux barres parallèles avec ceinture de lest."),
       ("Weighted dips", "Parallel bar dips with an added weight belt."),
       "pull_up_bar"),
    _e("rotations_bras_epaules", None, "mobility", [MB], E,
       ("Rotations des bras et épaules", "Circonférences amples des bras pour mobiliser la ceinture scapulaire."),
       ("Arm and shoulder circles", "Wide arm rotations to mobilize the shoulder girdle.")),
    _e("marche_rapide", None, "cardio", [CD, EN, RC], E,
       ("Marche rapide", "Marche active à allure soutenue en plein air ou sur tapis."),
       ("Brisk walking", "Active walking at a brisk pace outdoors or on a treadmill.")),
    _e("marche_active", None, "cardio", [CD, EN, RC], E,
       ("Marche active", "Marche continue pour relancer la circulation."),
       ("Active walking", "Continuous active walking to boost circulation.")),
    _e("etirements_doux_ischios_pecs", None, "mobility", [MB, RC], E,
       ("Étirements doux des ischio-jambiers et pectoraux", "Étirements légers et progressifs sans forcer."),
       ("Gentle hamstring and chest stretches", "Mild and progressive stretches without straining.")),
]
