SPORT_GOAL_MATRIX = {
    "musculation": {
        "hypertrophy": 0.95,
        "strength": 1.00,
        "power": 0.80,
        "body_recomposition": 0.90,
        "fat_loss": 0.75,
        "general_fitness": 0.70,
        "performance": 0.70,
        "endurance": 0.20,
    },
    "course": {
        "endurance": 1.00,
        "performance": 0.90,
        "speed": 0.70,
        "power": 0.50,
        "aerobic_capacity": 0.95,
        "fat_loss": 0.80,
        "general_fitness": 0.75,
        "conditioning": 0.80,
    },
    "football": {
        "endurance": 0.95,
        "speed": 1.00,
        "agility": 0.95,
        "power": 0.85,
        "acceleration": 0.90,
        "performance": 0.96,
        "conditioning": 0.90,
        "general_fitness": 0.75,
    },
    "basketball": {
        "speed": 0.96,
        "agility": 1.00,
        "power": 0.90,
        "endurance": 0.80,
        "performance": 0.95,
        "jumping": 0.80,
        "general_fitness": 0.80,
    },
    "cyclisme": {
        "endurance": 1.00,
        "performance": 0.90,
        "aerobic_capacity": 0.85,
        "fat_loss": 0.75,
        "general_fitness": 0.70,
        "conditioning": 0.80,
    },
    "natation": {
        "endurance": 0.95,
        "speed": 0.85,
        "technique": 0.90,
        "performance": 0.88,
        "aerobic_capacity": 0.80,
        "general_fitness": 0.75,
    },
    "boxe": {
        "conditioning": 1.00,
        "endurance": 0.90,
        "speed": 0.95,
        "power": 0.90,
        "technique": 0.85,
        "performance": 0.94,
        "general_fitness": 0.75,
    },
    "fitness": {
        "general_fitness": 1.00,
        "conditioning": 0.85,
        "fat_loss": 0.80,
        "body_recomposition": 0.80,
        "strength": 0.70,
        "mobility": 0.70,
    },
    "cardio": {
        "endurance": 0.90,
        "conditioning": 1.00,
        "fat_loss": 0.85,
        "general_fitness": 0.80,
        "aerobic_capacity": 0.90,
    },
    "arts_martiaux": {
        "technique": 1.00,
        "conditioning": 0.90,
        "speed": 0.85,
        "power": 0.80,
        "performance": 0.88,
        "general_fitness": 0.78,
    },
}
