
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb7b9f5d28f'
down_revision: Union[str, None] = '25bdecb2e173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('food_budget_per_week', sa.Numeric(precision=8, scale=2), nullable=True))
    op.drop_column('profiles', 'food_budget_per_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('food_budget_per_month', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'food_budget_per_week')
    # ### end Alembic commands ###
