"""replace food fixed price with flexible food prices

Revision ID: 6782d98f4e53
Revises: 3cb7b9f5d28f
Create Date: 2026-09-07 11:45:17.140889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6782d98f4e53'
down_revision: Union[str, None] = '3cb7b9f5d28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_prices',
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('price_da', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_prices_food_id'), 'food_prices', ['food_id'], unique=False)
    op.drop_column('foods', 'price_da_per_100g')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('price_da_per_100g', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_food_prices_food_id'), table_name='food_prices')
    op.drop_table('food_prices')
    # ### end Alembic commands ###
