"""add target macros to meal_plan_meals

Revision ID: 7e79087d273c
Revises: e0be5bafad88
Create Date: 2026-09-07 20:38:20.315887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e79087d273c'
down_revision: Union[str, None] = 'e0be5bafad88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_meals', sa.Column('target_calories_kcal', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('meal_plan_meals', sa.Column('target_protein_g', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('meal_plan_meals', sa.Column('target_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('meal_plan_meals', sa.Column('target_fat_g', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan_meals', 'target_fat_g')
    op.drop_column('meal_plan_meals', 'target_carbs_g')
    op.drop_column('meal_plan_meals', 'target_protein_g')
    op.drop_column('meal_plan_meals', 'target_calories_kcal')
    # ### end Alembic commands ###
