"""add open food facts / open prices sourcing fields

Revision ID: a1b2c3d4e5f6
Revises: e0be5bafad88
Create Date: 2026-09-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'e0be5bafad88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


halal_status_enum = sa.Enum('halal', 'not_halal', 'unknown', name='halal_status')
food_data_source_enum = sa.Enum('manual', 'open_food_facts', 'open_prices', name='food_data_source')
food_price_data_source_enum = sa.Enum('manual', 'open_food_facts', 'open_prices', name='food_price_data_source')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    halal_status_enum.create(bind, checkfirst=True)
    food_data_source_enum.create(bind, checkfirst=True)
    food_price_data_source_enum.create(bind, checkfirst=True)

    # --- foods ---
    op.add_column('foods', sa.Column('brand', sa.String(length=150), nullable=True))
    op.add_column('foods', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column(
        'foods',
        sa.Column(
            'halal_status',
            halal_status_enum,
            nullable=False,
            server_default='unknown',
        ),
    )
    op.add_column(
        'foods',
        sa.Column(
            'source',
            food_data_source_enum,
            nullable=False,
            server_default='manual',
        ),
    )
    op.add_column('foods', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('foods', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.add_column('foods', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_foods_source_id'), 'foods', ['source_id'], unique=False)
    op.create_index(op.f('ix_foods_barcode'), 'foods', ['barcode'], unique=True)

    # --- food_prices ---
    op.add_column(
        'food_prices',
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='DZD'),
    )
    op.add_column(
        'food_prices',
        sa.Column(
            'source',
            food_price_data_source_enum,
            nullable=False,
            server_default='manual',
        ),
    )
    op.add_column('food_prices', sa.Column('source_id', sa.String(length=150), nullable=True))
    op.add_column('food_prices', sa.Column('store_name', sa.String(length=150), nullable=True))
    op.add_column('food_prices', sa.Column('location', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_food_prices_source_id'), 'food_prices', ['source_id'], unique=False)

    # --- profiles ---
    op.add_column(
        'profiles',
        sa.Column('halal_required', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'halal_required')

    op.drop_index(op.f('ix_food_prices_source_id'), table_name='food_prices')
    op.drop_column('food_prices', 'location')
    op.drop_column('food_prices', 'store_name')
    op.drop_column('food_prices', 'source_id')
    op.drop_column('food_prices', 'source')
    op.drop_column('food_prices', 'currency')

    op.drop_index(op.f('ix_foods_barcode'), table_name='foods')
    op.drop_index(op.f('ix_foods_source_id'), table_name='foods')
    op.drop_column('foods', 'last_synced_at')
    op.drop_column('foods', 'barcode')
    op.drop_column('foods', 'source_id')
    op.drop_column('foods', 'source')
    op.drop_column('foods', 'halal_status')
    op.drop_column('foods', 'image_url')
    op.drop_column('foods', 'brand')

    bind = op.get_bind()
    food_price_data_source_enum.drop(bind, checkfirst=True)
    food_data_source_enum.drop(bind, checkfirst=True)
    halal_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
