"""add sport category goal and log session fields

Revision ID: bd541b7d8e51
Revises: c2a4b6d8e1f3
Create Date: 2026-09-10 20:53:05.643367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

sport_goal_enum = sa.Enum(
    'MUSCLE_GAIN', 'STRENGTH', 'FAT_LOSS', 'ENDURANCE', 'PERFORMANCE',
    'SPEED', 'POWER', 'GENERAL_FITNESS', 'HEALTH', name='sport_goal'
)


# revision identifiers, used by Alembic.
revision: str = 'bd541b7d8e51'
down_revision: Union[str, None] = 'c2a4b6d8e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('muscle_group', sa.String(length=100), nullable=True))
    op.add_column('sports', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('sports', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('sports', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    sport_goal_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user_sports', sa.Column('goal', sport_goal_enum, nullable=True))
    op.add_column('user_sports', sa.Column('preferred_duration_minutes', sa.SmallInteger(), nullable=True))
    op.add_column('user_sports', sa.Column('preferred_training_days', sa.ARRAY(sa.SmallInteger()), nullable=True))
    op.add_column('workout_logs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_logs', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_logs', sa.Column('overall_rpe', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('workout_logs', sa.Column('calories_burned', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('workout_logs', sa.Column('completed', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'completed')
    op.drop_column('workout_logs', 'calories_burned')
    op.drop_column('workout_logs', 'overall_rpe')
    op.drop_column('workout_logs', 'ended_at')
    op.drop_column('workout_logs', 'started_at')
    op.drop_column('user_sports', 'preferred_training_days')
    op.drop_column('user_sports', 'preferred_duration_minutes')
    op.drop_column('user_sports', 'goal')
    sport_goal_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('sports', 'is_active')
    op.drop_column('sports', 'description')
    op.drop_column('sports', 'category')
    op.drop_column('exercises', 'muscle_group')
    # ### end Alembic commands ###
