"""add_goals_equipment_and_training_preferences

Revision ID: c7d79267f89c
Revises: bd541b7d8e51
Create Date: 2026-09-11 08:28:40.265064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d79267f89c'
down_revision: Union[str, None] = 'bd541b7d8e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_category'), 'environments', ['category'], unique=False)
    op.create_index(op.f('ix_environments_slug'), 'environments', ['slug'], unique=True)
    op.create_table('equipment',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_category'), 'equipment', ['category'], unique=False)
    op.create_index(op.f('ix_equipment_slug'), 'equipment', ['slug'], unique=True)
    op.create_table('goals',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('BODY_COMPOSITION', 'PERFORMANCE', 'FITNESS_HEALTH', 'RECOVERY', name='goalcategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_slug'), 'goals', ['slug'], unique=True)
    op.create_table('environment_translations',
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'language_code', name='uq_environment_translation')
    )
    op.create_index(op.f('ix_environment_translations_environment_id'), 'environment_translations', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environment_translations_language_code'), 'environment_translations', ['language_code'], unique=False)
    op.create_table('equipment_translations',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'language_code', name='uq_equipment_translation')
    )
    op.create_index(op.f('ix_equipment_translations_equipment_id'), 'equipment_translations', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_translations_language_code'), 'equipment_translations', ['language_code'], unique=False)
    op.create_table('goal_translations',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'language_code', name='uq_goal_translation')
    )
    op.create_index(op.f('ix_goal_translations_goal_id'), 'goal_translations', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_translations_language_code'), 'goal_translations', ['language_code'], unique=False)
    op.create_table('sport_environment',
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'environment_id', name='uq_sport_environment')
    )
    op.create_index(op.f('ix_sport_environment_environment_id'), 'sport_environment', ['environment_id'], unique=False)
    op.create_index(op.f('ix_sport_environment_sport_id'), 'sport_environment', ['sport_id'], unique=False)
    op.create_table('sport_equipment',
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'equipment_id', name='uq_sport_equipment')
    )
    op.create_index(op.f('ix_sport_equipment_equipment_id'), 'sport_equipment', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sport_equipment_sport_id'), 'sport_equipment', ['sport_id'], unique=False)
    op.create_table('sport_goal_matrix',
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'goal_id', name='uq_sport_goal_matrix')
    )
    op.create_index(op.f('ix_sport_goal_matrix_goal_id'), 'sport_goal_matrix', ['goal_id'], unique=False)
    op.create_index(op.f('ix_sport_goal_matrix_sport_id'), 'sport_goal_matrix', ['sport_id'], unique=False)
    op.create_table('training_constraints',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('constraint_type', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_constraints_category'), 'training_constraints', ['category'], unique=False)
    op.create_index(op.f('ix_training_constraints_constraint_type'), 'training_constraints', ['constraint_type'], unique=False)
    op.create_index(op.f('ix_training_constraints_user_id'), 'training_constraints', ['user_id'], unique=False)
    op.create_table('training_preferences',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('preferred_days', sa.String(length=200), nullable=True),
    sa.Column('preferred_time', sa.String(length=80), nullable=True),
    sa.Column('preferred_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('preferred_training_types', sa.String(length=200), nullable=True),
    sa.Column('disliked_exercises', sa.String(length=500), nullable=True),
    sa.Column('preferred_sports', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_preferences_user_id'), 'training_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_preferences_user_id'), table_name='training_preferences')
    op.drop_table('training_preferences')
    op.drop_index(op.f('ix_training_constraints_user_id'), table_name='training_constraints')
    op.drop_index(op.f('ix_training_constraints_constraint_type'), table_name='training_constraints')
    op.drop_index(op.f('ix_training_constraints_category'), table_name='training_constraints')
    op.drop_table('training_constraints')
    op.drop_index(op.f('ix_sport_goal_matrix_sport_id'), table_name='sport_goal_matrix')
    op.drop_index(op.f('ix_sport_goal_matrix_goal_id'), table_name='sport_goal_matrix')
    op.drop_table('sport_goal_matrix')
    op.drop_index(op.f('ix_sport_equipment_sport_id'), table_name='sport_equipment')
    op.drop_index(op.f('ix_sport_equipment_equipment_id'), table_name='sport_equipment')
    op.drop_table('sport_equipment')
    op.drop_index(op.f('ix_sport_environment_sport_id'), table_name='sport_environment')
    op.drop_index(op.f('ix_sport_environment_environment_id'), table_name='sport_environment')
    op.drop_table('sport_environment')
    op.drop_index(op.f('ix_goal_translations_language_code'), table_name='goal_translations')
    op.drop_index(op.f('ix_goal_translations_goal_id'), table_name='goal_translations')
    op.drop_table('goal_translations')
    op.drop_index(op.f('ix_equipment_translations_language_code'), table_name='equipment_translations')
    op.drop_index(op.f('ix_equipment_translations_equipment_id'), table_name='equipment_translations')
    op.drop_table('equipment_translations')
    op.drop_index(op.f('ix_environment_translations_language_code'), table_name='environment_translations')
    op.drop_index(op.f('ix_environment_translations_environment_id'), table_name='environment_translations')
    op.drop_table('environment_translations')
    op.drop_index(op.f('ix_goals_slug'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_equipment_slug'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_category'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_environments_slug'), table_name='environments')
    op.drop_index(op.f('ix_environments_category'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
