"""add food unit weight

Revision ID: e0be5bafad88
Revises: 6782d98f4e53
Create Date: 2026-09-07 17:19:16.548021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0be5bafad88'
down_revision: Union[str, None] = '6782d98f4e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('unit_weight_g', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'unit_weight_g')
    # ### end Alembic commands ###
