
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ca8c4593df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_liquid', sa.Boolean(), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('saturated_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_unit', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_slug'), 'foods', ['slug'], unique=True)
    op.create_table('recipes',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('prep_time_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('cook_time_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_level'), nullable=True),
    sa.Column('servings', sa.SmallInteger(), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_cost_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_halal', sa.Boolean(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.create_table('sports',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_slug'), 'sports', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=30), nullable=True),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_changed_at'), 'audit_logs', ['changed_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('body_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('WEIGHT', 'HEIGHT', 'BODY_FAT_PERCENTAGE', 'CHEST', 'WAIST', 'HIPS', 'ARM', 'THIGH', 'CALF', 'NECK', name='body_metric_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_metric_type'), 'body_measurements', ['metric_type'], unique=False)
    op.create_index(op.f('ix_body_measurements_recorded_at'), 'body_measurements', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_index(op.f('ix_exercises_sport_id'), 'exercises', ['sport_id'], unique=False)
    op.create_table('food_translations',
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'language_code', name='uq_food_translation')
    )
    op.create_index(op.f('ix_food_translations_food_id'), 'food_translations', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_translations_language_code'), 'food_translations', ['language_code'], unique=False)
    op.create_table('inventories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('inventory_type', sa.Enum('FRIDGE', 'FREEZER', 'PANTRY', name='inventory_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'inventory_type', name='uq_user_inventory_type')
    )
    op.create_index(op.f('ix_inventories_user_id'), 'inventories', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('goal', sa.Enum('WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN', 'PERFORMANCE', 'ENDURANCE', 'STRENGTH', 'GENERAL_HEALTH', 'BODY_RECOMPOSITION', name='meal_plan_goal_type'), nullable=True),
    sa.Column('target_calories_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('target_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='meal_type'), nullable=False),
    sa.Column('consumed_on', sa.Date(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('total_calories_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('total_protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_consumed_on'), 'meals', ['consumed_on'], unique=False)
    op.create_index('ix_meals_user_date', 'meals', ['user_id', 'consumed_on'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('MEAL_REMINDER', 'WATER_REMINDER', 'TRAINING_REMINDER', 'GENERAL', name='notification_type'), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('current_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activity_level'), nullable=True),
    sa.Column('primary_goal', sa.Enum('WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN', 'PERFORMANCE', 'ENDURANCE', 'STRENGTH', 'GENERAL_HEALTH', 'BODY_RECOMPOSITION', name='goal_type'), nullable=True),
    sa.Column('unit_system', sa.Enum('METRIC', 'IMPERIAL', name='unit_system'), nullable=False),
    sa.Column('dietary_preferences', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('food_budget_per_month', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('G', 'KG', 'ML', 'L', 'PIECE', 'TBSP', 'TSP', 'CUP', 'SERVING', name='recipe_ingredient_unit'), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_food_id'), 'recipe_ingredients', ['food_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_steps',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.SmallInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'step_number', name='uq_recipe_step_number')
    )
    op.create_index(op.f('ix_recipe_steps_recipe_id'), 'recipe_steps', ['recipe_id'], unique=False)
    op.create_table('recipe_translations',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'language_code', name='uq_recipe_translation')
    )
    op.create_index(op.f('ix_recipe_translations_language_code'), 'recipe_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_recipe_translations_recipe_id'), 'recipe_translations', ['recipe_id'], unique=False)
    op.create_table('recipe_videos',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'VIMEO', 'TIKTOK', 'INSTAGRAM', 'INTERNAL', name='video_platform'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_videos_recipe_id'), 'recipe_videos', ['recipe_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sleep_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Enum('POOR', 'FAIR', 'GOOD', 'EXCELLENT', name='sleep_quality'), nullable=True),
    sa.Column('fatigue_level', sa.SmallInteger(), nullable=True),
    sa.Column('stress_level', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sleep_date', name='uq_sleep_log_user_date')
    )
    op.create_index(op.f('ix_sleep_logs_sleep_date'), 'sleep_logs', ['sleep_date'], unique=False)
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    op.create_table('sport_translations',
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'language_code', name='uq_sport_translation')
    )
    op.create_index(op.f('ix_sport_translations_language_code'), 'sport_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_sport_translations_sport_id'), 'sport_translations', ['sport_id'], unique=False)
    op.create_table('training_programs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programs_user_id'), 'training_programs', ['user_id'], unique=False)
    op.create_table('user_sports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='sport_level'), nullable=True),
    sa.Column('frequency_per_week', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sport_id', name='uq_user_sport')
    )
    op.create_index(op.f('ix_user_sports_sport_id'), 'user_sports', ['sport_id'], unique=False)
    op.create_index(op.f('ix_user_sports_user_id'), 'user_sports', ['user_id'], unique=False)
    op.create_index('ix_user_sports_user_primary', 'user_sports', ['user_id', 'is_primary'], unique=False)
    op.create_table('water_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ml', sa.SmallInteger(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_logged_on'), 'water_logs', ['logged_on'], unique=False)
    op.create_index('ix_water_logs_user_date', 'water_logs', ['user_id', 'logged_on'], unique=False)
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    op.create_table('exercise_translations',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'language_code', name='uq_exercise_translation')
    )
    op.create_index(op.f('ix_exercise_translations_exercise_id'), 'exercise_translations', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_translations_language_code'), 'exercise_translations', ['language_code'], unique=False)
    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('G', 'KG', 'ML', 'L', 'PIECE', 'TBSP', 'TSP', 'CUP', 'SERVING', name='inventory_measurement_unit'), nullable=False),
    sa.Column('added_on', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_expires_on'), 'inventory_items', ['expires_on'], unique=False)
    op.create_index(op.f('ix_inventory_items_food_id'), 'inventory_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('G', 'KG', 'ML', 'L', 'PIECE', 'TBSP', 'TSP', 'CUP', 'SERVING', name='measurement_unit'), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    op.create_table('meal_photo_analyses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'CORRECTED', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('resulting_meal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resulting_meal_id'], ['meals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_photo_analyses_user_id'), 'meal_photo_analyses', ['user_id'], unique=False)
    op.create_table('meal_plan_days',
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_days_meal_plan_id'), 'meal_plan_days', ['meal_plan_id'], unique=False)
    op.create_index('ix_meal_plan_days_plan_number', 'meal_plan_days', ['meal_plan_id', 'day_number'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=True),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_setting_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('MEAL_REMINDER', 'WATER_REMINDER', 'TRAINING_REMINDER', 'GENERAL', name='notification_log_type'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_setting_id'], ['notification_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_sent_at'), 'notification_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('recipe_step_translations',
    sa.Column('recipe_step_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_step_id'], ['recipe_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_step_id', 'language_code', name='uq_recipe_step_translation')
    )
    op.create_index(op.f('ix_recipe_step_translations_language_code'), 'recipe_step_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_recipe_step_translations_recipe_step_id'), 'recipe_step_translations', ['recipe_step_id'], unique=False)
    op.create_table('workouts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_program_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_training_program_id'), 'workouts', ['training_program_id'], unique=False)
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('meal_photo_analysis_items',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('detected_label', sa.String(length=150), nullable=False),
    sa.Column('matched_food_id', sa.UUID(), nullable=True),
    sa.Column('estimated_portion', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('estimated_unit', sa.String(length=10), nullable=True),
    sa.Column('estimated_calories_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('estimated_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('corrected_food_id', sa.UUID(), nullable=True),
    sa.Column('corrected_portion', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['meal_photo_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrected_food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_photo_analysis_items_analysis_id'), 'meal_photo_analysis_items', ['analysis_id'], unique=False)
    op.create_table('meal_plan_meals',
    sa.Column('meal_plan_day_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='meal_plan_meal_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_day_id'], ['meal_plan_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_meals_meal_plan_day_id'), 'meal_plan_meals', ['meal_plan_day_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercises_exercise_id'), 'workout_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercises_workout_id'), 'workout_exercises', ['workout_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('based_on_workout_id', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['based_on_workout_id'], ['workouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_performed_at'), 'workout_logs', ['performed_at'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_index('ix_workout_logs_user_performed', 'workout_logs', ['user_id', 'performed_at'], unique=False)
    op.create_table('meal_plan_meal_items',
    sa.Column('meal_plan_meal_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('G', 'KG', 'ML', 'L', 'PIECE', 'TBSP', 'TSP', 'CUP', 'SERVING', name='meal_plan_measurement_unit'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_plan_meal_id'], ['meal_plan_meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_meal_items_meal_plan_meal_id'), 'meal_plan_meal_items', ['meal_plan_meal_id'], unique=False)
    op.create_table('workout_log_exercises',
    sa.Column('workout_log_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_log_exercises_exercise_id'), 'workout_log_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_log_exercises_workout_log_id'), 'workout_log_exercises', ['workout_log_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('workout_exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('target_reps', sa.SmallInteger(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('target_distance_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_workout_exercise_id'), 'workout_sets', ['workout_exercise_id'], unique=False)
    op.create_table('workout_log_sets',
    sa.Column('workout_log_exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workout_log_exercise_id'], ['workout_log_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_log_sets_workout_log_exercise_id'), 'workout_log_sets', ['workout_log_exercise_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.Enum('MAX_WEIGHT', 'MAX_REPS', 'ONE_REP_MAX', 'BEST_TIME', 'BEST_DISTANCE', 'MAX_DURATION', name='record_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_set_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_set_id'], ['workout_log_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_records_achieved_at'), 'personal_records', ['achieved_at'], unique=False)
    op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    op.create_index('ix_personal_records_user_type', 'personal_records', ['user_id', 'record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_personal_records_user_type', table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_achieved_at'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_workout_log_sets_workout_log_exercise_id'), table_name='workout_log_sets')
    op.drop_table('workout_log_sets')
    op.drop_index(op.f('ix_workout_sets_workout_exercise_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_workout_log_exercises_workout_log_id'), table_name='workout_log_exercises')
    op.drop_index(op.f('ix_workout_log_exercises_exercise_id'), table_name='workout_log_exercises')
    op.drop_table('workout_log_exercises')
    op.drop_index(op.f('ix_meal_plan_meal_items_meal_plan_meal_id'), table_name='meal_plan_meal_items')
    op.drop_table('meal_plan_meal_items')
    op.drop_index('ix_workout_logs_user_performed', table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_performed_at'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_workout_exercises_workout_id'), table_name='workout_exercises')
    op.drop_index(op.f('ix_workout_exercises_exercise_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_meal_plan_meals_meal_plan_day_id'), table_name='meal_plan_meals')
    op.drop_table('meal_plan_meals')
    op.drop_index(op.f('ix_meal_photo_analysis_items_analysis_id'), table_name='meal_photo_analysis_items')
    op.drop_table('meal_photo_analysis_items')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_training_program_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_recipe_step_translations_recipe_step_id'), table_name='recipe_step_translations')
    op.drop_index(op.f('ix_recipe_step_translations_language_code'), table_name='recipe_step_translations')
    op.drop_table('recipe_step_translations')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_sent_at'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_meal_plan_days_plan_number', table_name='meal_plan_days')
    op.drop_index(op.f('ix_meal_plan_days_meal_plan_id'), table_name='meal_plan_days')
    op.drop_table('meal_plan_days')
    op.drop_index(op.f('ix_meal_photo_analyses_user_id'), table_name='meal_photo_analyses')
    op.drop_table('meal_photo_analyses')
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_food_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_expires_on'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_exercise_translations_language_code'), table_name='exercise_translations')
    op.drop_index(op.f('ix_exercise_translations_exercise_id'), table_name='exercise_translations')
    op.drop_table('exercise_translations')
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_index('ix_water_logs_user_date', table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_logged_on'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index('ix_user_sports_user_primary', table_name='user_sports')
    op.drop_index(op.f('ix_user_sports_user_id'), table_name='user_sports')
    op.drop_index(op.f('ix_user_sports_sport_id'), table_name='user_sports')
    op.drop_table('user_sports')
    op.drop_index(op.f('ix_training_programs_user_id'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_sport_translations_sport_id'), table_name='sport_translations')
    op.drop_index(op.f('ix_sport_translations_language_code'), table_name='sport_translations')
    op.drop_table('sport_translations')
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_sleep_date'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_recipe_videos_recipe_id'), table_name='recipe_videos')
    op.drop_table('recipe_videos')
    op.drop_index(op.f('ix_recipe_translations_recipe_id'), table_name='recipe_translations')
    op.drop_index(op.f('ix_recipe_translations_language_code'), table_name='recipe_translations')
    op.drop_table('recipe_translations')
    op.drop_index(op.f('ix_recipe_steps_recipe_id'), table_name='recipe_steps')
    op.drop_table('recipe_steps')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_food_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index('ix_meals_user_date', table_name='meals')
    op.drop_index(op.f('ix_meals_consumed_on'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_inventories_user_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_food_translations_language_code'), table_name='food_translations')
    op.drop_index(op.f('ix_food_translations_food_id'), table_name='food_translations')
    op.drop_table('food_translations')
    op.drop_index(op.f('ix_exercises_sport_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_recorded_at'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_metric_type'), table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_changed_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sports_slug'), table_name='sports')
    op.drop_table('sports')
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_foods_slug'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
